/** Windows/USB scan codes for common keys (KeyboardEvent.code → scan). */
const SCAN: Record<string, { scan: number; extended?: boolean }> = {
  Escape: { scan: 0x01 },
  Digit1: { scan: 0x02 },
  Digit2: { scan: 0x03 },
  Digit3: { scan: 0x04 },
  Digit4: { scan: 0x05 },
  Digit5: { scan: 0x06 },
  Digit6: { scan: 0x07 },
  Digit7: { scan: 0x08 },
  Digit8: { scan: 0x09 },
  Digit9: { scan: 0x0a },
  Digit0: { scan: 0x0b },
  Minus: { scan: 0x0c },
  Equal: { scan: 0x0d },
  Backspace: { scan: 0x0e },
  Tab: { scan: 0x0f },
  KeyQ: { scan: 0x10 },
  KeyW: { scan: 0x11 },
  KeyE: { scan: 0x12 },
  KeyR: { scan: 0x13 },
  KeyT: { scan: 0x14 },
  KeyY: { scan: 0x15 },
  KeyU: { scan: 0x16 },
  KeyI: { scan: 0x17 },
  KeyO: { scan: 0x18 },
  KeyP: { scan: 0x19 },
  BracketLeft: { scan: 0x1a },
  BracketRight: { scan: 0x1b },
  Enter: { scan: 0x1c },
  ControlLeft: { scan: 0x1d },
  KeyA: { scan: 0x1e },
  KeyS: { scan: 0x1f },
  KeyD: { scan: 0x20 },
  KeyF: { scan: 0x21 },
  KeyG: { scan: 0x22 },
  KeyH: { scan: 0x23 },
  KeyJ: { scan: 0x24 },
  KeyK: { scan: 0x25 },
  KeyL: { scan: 0x26 },
  Semicolon: { scan: 0x27 },
  Quote: { scan: 0x28 },
  Backquote: { scan: 0x29 },
  ShiftLeft: { scan: 0x2a },
  Backslash: { scan: 0x2b },
  KeyZ: { scan: 0x2c },
  KeyX: { scan: 0x2d },
  KeyC: { scan: 0x2e },
  KeyV: { scan: 0x2f },
  KeyB: { scan: 0x30 },
  KeyN: { scan: 0x31 },
  KeyM: { scan: 0x32 },
  Comma: { scan: 0x33 },
  Period: { scan: 0x34 },
  Slash: { scan: 0x35 },
  ShiftRight: { scan: 0x36 },
  NumpadMultiply: { scan: 0x37 },
  AltLeft: { scan: 0x38 },
  Space: { scan: 0x39 },
  CapsLock: { scan: 0x3a },
  F1: { scan: 0x3b },
  F2: { scan: 0x3c },
  F3: { scan: 0x3d },
  F4: { scan: 0x3e },
  F5: { scan: 0x3f },
  F6: { scan: 0x40 },
  F7: { scan: 0x41 },
  F8: { scan: 0x42 },
  F9: { scan: 0x43 },
  F10: { scan: 0x44 },
  NumLock: { scan: 0x45 },
  ScrollLock: { scan: 0x46 },
  Numpad7: { scan: 0x47 },
  Numpad8: { scan: 0x48 },
  Numpad9: { scan: 0x49 },
  NumpadSubtract: { scan: 0x4a },
  Numpad4: { scan: 0x4b },
  Numpad5: { scan: 0x4c },
  Numpad6: { scan: 0x4d },
  NumpadAdd: { scan: 0x4e },
  Numpad1: { scan: 0x4f },
  Numpad2: { scan: 0x50 },
  Numpad3: { scan: 0x51 },
  Numpad0: { scan: 0x52 },
  NumpadDecimal: { scan: 0x53 },
  F11: { scan: 0x57 },
  F12: { scan: 0x58 },
  ControlRight: { scan: 0x1d, extended: true },
  AltRight: { scan: 0x38, extended: true },
  Insert: { scan: 0x52, extended: true },
  Delete: { scan: 0x53, extended: true },
  Home: { scan: 0x47, extended: true },
  End: { scan: 0x4f, extended: true },
  PageUp: { scan: 0x49, extended: true },
  PageDown: { scan: 0x51, extended: true },
  ArrowLeft: { scan: 0x4b, extended: true },
  ArrowRight: { scan: 0x4d, extended: true },
  ArrowUp: { scan: 0x48, extended: true },
  ArrowDown: { scan: 0x50, extended: true },
  NumpadEnter: { scan: 0x1c, extended: true },
  NumpadDivide: { scan: 0x35, extended: true },
};

export function scanCodeForKey(code: string): { scan: number; extended: boolean } | null {
  const entry = SCAN[code];
  if (!entry) return null;
  return { scan: entry.scan, extended: entry.extended ?? false };
}
